name: socialapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #----- State Management -----#
  # bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  #----- UI -----#
  font_awesome_flutter: ^10.7.0

  #----- Utils -----#
  #----- Firebase -----#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/utils/
  fonts:
    - family: RalewayExtraLight
      fonts:
        - asset: assets/fonts/Raleway-ExtraLight.ttf
    - family: RalewayThin
      fonts:
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: RalewaySemiBold
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 300
    - family: OpenSansLight
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

